-- 0011 — DB integrity + hot-path indexes (DB-1/4/6/7/10).
-- Hand-added data clean-up runs FIRST so the constraints below apply on
-- existing dev DBs. Nothing here drops a table or a data column.
-- (a) DB-6: normalise values the new CHECKs / NOT NULL would reject.
UPDATE "agent_runs" SET "status" = 'failed' WHERE "status" IS NULL OR "status" NOT IN ('running', 'done', 'failed', 'cancelled');--> statement-breakpoint
UPDATE "findings" SET "severity" = upper("severity") WHERE "severity" NOT IN ('CRITICAL', 'WARNING', 'SUGGESTION') AND upper("severity") IN ('CRITICAL', 'WARNING', 'SUGGESTION');--> statement-breakpoint
UPDATE "findings" SET "severity" = 'SUGGESTION' WHERE "severity" NOT IN ('CRITICAL', 'WARNING', 'SUGGESTION');--> statement-breakpoint
UPDATE "pull_requests" SET "status" = 'needs_review' WHERE "status" NOT IN ('needs_review', 'reviewed', 'stale', 'open', 'closed', 'merged');--> statement-breakpoint
-- (b) DB-4: detach orphans before the new FKs (review rows are kept).
UPDATE "reviews" SET "run_id" = NULL WHERE "run_id" IS NOT NULL AND NOT EXISTS (SELECT 1 FROM "agent_runs" a WHERE a."id" = "reviews"."run_id");--> statement-breakpoint
UPDATE "reviews" SET "agent_id" = NULL WHERE "agent_id" IS NOT NULL AND NOT EXISTS (SELECT 1 FROM "agents" a WHERE a."id" = "reviews"."agent_id");--> statement-breakpoint
-- (c) DB-10: dedupe rows that only differed by a NULL before NULLS NOT DISTINCT
-- (keep the most recently written row = highest ctid; settings has no timestamp).
DELETE FROM "settings" a USING "settings" b WHERE a."workspace_id" = b."workspace_id" AND a."user_id" IS NOT DISTINCT FROM b."user_id" AND a."key" = b."key" AND a.ctid < b.ctid;--> statement-breakpoint
DELETE FROM "symbols" a USING "symbols" b WHERE a."repo_id" = b."repo_id" AND a."path" = b."path" AND a."name" = b."name" AND a."kind" = b."kind" AND a."line" IS NOT DISTINCT FROM b."line" AND a.ctid < b.ctid;--> statement-breakpoint
-- (d) Generated by drizzle-kit.
DROP INDEX "settings_ws_user_key_uq";--> statement-breakpoint
DROP INDEX "symbols_repo_path_name_kind_line_uq";--> statement-breakpoint
ALTER TABLE "agent_runs" ALTER COLUMN "status" SET DEFAULT 'running';--> statement-breakpoint
ALTER TABLE "agent_runs" ALTER COLUMN "status" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_run_id_agent_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."agent_runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "pr_commits_pr_idx" ON "pr_commits" USING btree ("pr_id");--> statement-breakpoint
CREATE INDEX "pr_files_pr_idx" ON "pr_files" USING btree ("pr_id");--> statement-breakpoint
CREATE INDEX "findings_review_idx" ON "findings" USING btree ("review_id");--> statement-breakpoint
CREATE INDEX "reviews_pr_created_idx" ON "reviews" USING btree ("pr_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "reviews_run_idx" ON "reviews" USING btree ("run_id");--> statement-breakpoint
CREATE INDEX "agent_runs_pr_ran_idx" ON "agent_runs" USING btree ("pr_id","ran_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "agent_runs_pr_running_idx" ON "agent_runs" USING btree ("pr_id") WHERE "agent_runs"."status" = 'running';--> statement-breakpoint
ALTER TABLE "settings" ADD CONSTRAINT "settings_ws_user_key_uq" UNIQUE NULLS NOT DISTINCT("workspace_id","user_id","key");--> statement-breakpoint
ALTER TABLE "symbols" ADD CONSTRAINT "symbols_repo_path_name_kind_line_uq" UNIQUE NULLS NOT DISTINCT("repo_id","path","name","kind","line");--> statement-breakpoint
ALTER TABLE "pull_requests" ADD CONSTRAINT "pull_requests_status_chk" CHECK ("pull_requests"."status" IN ('needs_review', 'reviewed', 'stale', 'open', 'closed', 'merged'));--> statement-breakpoint
ALTER TABLE "findings" ADD CONSTRAINT "findings_severity_chk" CHECK ("findings"."severity" IN ('CRITICAL', 'WARNING', 'SUGGESTION'));--> statement-breakpoint
ALTER TABLE "agent_runs" ADD CONSTRAINT "agent_runs_status_chk" CHECK ("agent_runs"."status" IN ('running', 'done', 'failed', 'cancelled'));
