import type React from "react";

const iconBtnBase: React.CSSProperties = {
  display: "inline-flex",
  alignItems: "center",
  justifyContent: "center",
  borderRadius: 5,
  color: "var(--text-muted)",
  cursor: "pointer",
  flexShrink: 0,
};

export const s = {
  list: { display: "flex", flexDirection: "column", gap: 8 } as React.CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    width: "100%",
    padding: "10px 14px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    textAlign: "left",
  } as React.CSSProperties,
  // Commits are markers, not actions — lighter (dashed, transparent) so they read
  // as separators between the runs they sit chronologically between.
  commitRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    width: "100%",
    padding: "8px 14px",
    borderRadius: 8,
    border: "1px dashed var(--border)",
    background: "transparent",
  } as React.CSSProperties,
  commitIcon: { color: "var(--text-muted)", flexShrink: 0 } as React.CSSProperties,
  commitSha: { fontSize: 12, color: "var(--text-secondary)", flexShrink: 0 } as React.CSSProperties,
  commitMsg: {
    fontSize: 12.5,
    color: "var(--text-secondary)",
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } as React.CSSProperties,
  commitMeta: { fontSize: 11, color: "var(--text-muted)", flexShrink: 0 } as React.CSSProperties,
  runMain: { display: "flex", flexDirection: "column", gap: 2, flex: 1, minWidth: 0 } as React.CSSProperties,
  runTitle: { fontSize: 13, fontWeight: 600, color: "var(--text-primary)" } as React.CSSProperties,
  agentLink: (clickable: boolean): React.CSSProperties => ({
    background: "none",
    border: "none",
    padding: 0,
    font: "inherit",
    fontWeight: 600,
    color: "var(--text-primary)",
    cursor: clickable ? "pointer" : "default",
    textDecoration: clickable ? "underline" : "none",
    textDecorationStyle: "dotted",
    textUnderlineOffset: 3,
  }),
  model: { fontSize: 12, fontWeight: 400, color: "var(--text-muted)" } as React.CSSProperties,
  error: {
    fontSize: 12,
    color: "var(--crit)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } as React.CSSProperties,
  runMeta: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: 2,
    fontSize: 11,
    color: "var(--text-muted)",
    flexShrink: 0,
  } as React.CSSProperties,
  traceBtn: {
    ...iconBtnBase,
    padding: 4,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } as React.CSSProperties,
  deleteBtn: { ...iconBtnBase, padding: 3, border: "none", background: "none" } as React.CSSProperties,
  findings: { display: "flex", alignItems: "center", gap: 4, fontSize: 12, color: "var(--text-muted)" } as React.CSSProperties,
};
